### ISSUE TITLE
Use optional/required etag, when available, in Delete method tests

### ISSUE THREAD

**Issue by fredrikaverpil** [einride/protoc-gen-go-aip-test#239]
AIP-135 talks about [Protected Delete](https://google.aip.dev/135#protected-delete), which entails requiring etag in the proto.

However, the tests for the Delete method does not take etag into account right now. We aim to fix this and is internally tracked as TRA-1554.

Note: there is a conflicting bug in googleapis/api-linter for this currently: https://github.com/googleapis/api-linter/issues/1395

**Comment by thall** [comment]
@fredrikaverpil can this be closed now since we have tests takes the etag into account?
https://github.com/einride/protoc-gen-go-aip-test/blob/master/internal/aiptest/deletion/etag.go
